### ISSUE TITLE
emacs winner mode like feature for window manager

### ISSUE THREAD

**Issue by QiangF** [nlfiasel/.doom.d#1]
以前用EXWM，窗口排布可以用winner切换，现在被迫用openbox，想实现一个类似的功能，
这里有个参考脚本
https://github.com/BlaineEXE/window-layout
要和窗口管理器深度整合估计要这个
https://github.com/baverman/orcsome

**Comment by nlfiasel** [comment]
https://github.com/capn-damo/Openbox-tiling

**Comment by QiangF** [comment]
不是，emacs winner mode (或者 eyebrowse) 主要两个功能，winner-undo 和 winnner redo，就是恢复上一个桌面窗口布置，一个布置可能有好多窗口，窗口之间甚至可以部分重叠。

window-layout 可以保存窗口排布，orcsome 可以在窗口变化时加 hook，感觉把这些和 openbox xkeysnail 整合，可以得到一个无比强大的跨界窗口管理器

**Comment by nlfiasel** [comment]
明白你意思了...就是给layout加快照...?

改天试试

**Comment by nlfiasel** [comment]
https://github.com/nlfiasel/orcsome-desktop-snapshot

**Comment by QiangF** [comment]
厉害！有空一定好好研究下。
